name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: repo

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        working-directory: repo/V2rayNG
        run: chmod +x ./gradlew

      - name: Build Debug APK
        working-directory: repo/V2rayNG
        run: ./gradlew assembleDebug